### ISSUE TITLE
GPU speed-up for small systems 

### ISSUE THREAD

**Issue by bensonbits** [lorenzo-rovigatti/oxDNA#1]
Hi,

The GPU speedup is really great for larger systems like DNA origami, but is small for small systems. Presumably this is due to there being more GPU cores than nucleotides? It would be nice if was possible to run several small systems at the same time on one GPU to better use the GPU cores. Essentially putting many small systems in separate and non interacting boxes and simulating them at the same time. 

Might be difficult to implement though :) 

Cheers 

Erik

**Comment by mckwxp** [comment]
Maybe you could try running multiple oxDNA processes on the same GPU card? Probably each simulation will slow down a bit, but hopefully by less than 1/N_processes.

**Comment by lorenzo-rovigatti** [comment]
You can surely do that. The problem is that the GPU architecture makes it really unefficient to simulate few particles. With oxDNA, the GPU performance starts to shine when the number of particles exceeds a few thousands (per process, not in total).

**Comment by ErikPoppleton** [comment]
Years late, but we tried running multiple small oxDNA simulations on the same A100 card and they were more than 10x slower than running them on separate cards, so unfortunately it looks like the current setup does not benefit from this.

**Comment by supers1x** [comment]
> Years late, but we tried running multiple small oxDNA simulations on the same A100 card and they were more than 10x slower than running them on separate cards, so unfortunately it looks like the current setup does not benefit from this.

Maybe you could try Nvidia's [Multi-Process Service](http://docs.nvidia.com/deploy/mps/index.html).
I usually run 6 simulations (100~400 nucleotides) simultaneously on an RTX3080 card for production simulation. For overall speed, it is  4x faster than one simulation.

**Comment by lorenzo-rovigatti** [comment]
Well, this sounds really interesting. I have never used that tool... can you share how to use oxDNA with it?

**Comment by supers1x** [comment]
On my server, just run these shell commands after the server is started.  As for HPC, you can ask the administrator for help. 
``` 
export CUDA_VISIBLE_DEVICES=0          # take GPU0 for example
nvidia-smi -i 0 -c EXCLUSIVE_PROCESS  # enable Exclusive Process on GPU0
nvidia-cuda-mps-control -d                   # start the mps service
```
Then you can run the oxDNA program as usual. Run `nvidia-smi` to monitor GPU utility and whether the processes type of oxDNA changes from `C` to `M+C`.

**Comment by lorenzo-rovigatti** [comment]
Thank you very much, I'll give it a try.

**Comment by ErikPoppleton** [comment]
I just gave this a try on an A100 GPU for a 90 nt system and it worked beautifully:
1 exclusive process - 0.0500823 ms/step
3 processes on mps - 0.0537173 0.0576431, 0.0571805 ms/step
1 CPU process - 0.166495

**Comment by ErikPoppleton** [comment]
I also tried it on a 27058 nt system and the result was the same:
1 exclusive process - 0.190249
4 processes on mps -  0.231056, 0.229485, 0.199157, 0.198948
So it looks like, at least if you have A100s (or H100s), you can run many, many instances of oxDNA on the same GPU without degrading performance.

**Comment by ErikPoppleton** [comment]
Also tried on an A6000.  There, the performance does degrade once you go past 3 simulations, but it's roughly half as fast, and doesn't degrade further between 3 and 48 simulations for a 6600 nt system.  For a 14000 nt system, I was only able to run 22 simulations before running out of memory, but the same pattern was present.

**Comment by RodenLuo** [comment]
I happened to run on A6000 for this yesterday too. I also observed the similar and have not figured out why (some insights below). I also tested on A100. Here are some stats. 

For the 132 nt [RNA tile](https://github.com/lorenzo-rovigatti/oxDNA/tree/master/analysis/paper_examples/clustering), RNA2 MD, steps = 1e7, print_conf_interval = 1e3, print_energy_every = 1e3. 

**One job on A6000 without MPS**

INFO: Total Running Time: 658.549 s, per step: 0.0658549 ms

**48 jobs on A6000 with MPS**

INFO: Total Running Time: 3994.01 s, per step: 0.399401 ms

**One job on A100 without MPS**

INFO: Total Running Time: 780.25 s, per step: 0.078025 ms

**10 jobs on A100 with MPS**

INFO: Total Running Time: 993.66 s, per step: 0.099366 ms

The A6000 is a local machine, with 64 CPUs (2 sockets, each with 16 cores, each with 2 threads). For the A100, it's a node from a cluster, I only asked for one CPU for the A100 (I might need to ask more). On my TODO is to check the memory communication between the GPU ID and the CPU socket ID. If I recall correctly, when there are multiple GPUs and multiple CPU sockets, there are dedicated memory links between certain CPUs and GPUs. So, it might happen that the memory communication between CPU thread id 0 and GPU 0 is much faster than that between CPU thread id 0 and GPU 3 (in my case for A6000) or GPU 7 (in some of my cases for A100). 

Also, for me, the 132 nt system already requires 961MiB GPU mem. And one A6000 with 49140MiB mem can only harbor a maximum of 48 runs.

**Comment by RodenLuo** [comment]
Thanks! I think these two figures explain it. The figures are for NVIDIA DGX Server A100. For cores on CPU0 to communicate with GPU 4-7, they have to go through an extra layer, the NVSwitch. On rare occasions, even without MPS, one might hit this scenario and have lower performance than usual. 

![image](https://user-images.githubusercontent.com/8460424/184955032-7927ebbb-1681-4b18-9bc1-73f84a7825ae.png)

![image](https://user-images.githubusercontent.com/8460424/184955438-5f29991b-01f2-4495-90d1-833bf4aff62d.png)

**Comment by lorenzo-rovigatti** [comment]
Thanks everyone for their detailed feedback. Is anyone willing to write a short paragraph summarising your findings that can be added to the docs?

**Comment by ErikPoppleton** [comment]
Okay, it's been a year, but I finally did this.  Turns out you can get quite significant increases in throughput on smaller systems (origamis still count as smaller) by using MPS.  The details of my analysis can be found in the new [scaling page](https://lorenzo-rovigatti.github.io/oxDNA/scaling.html) of the documentation.
