### ISSUE TITLE
Templates remaining in contrib/romano

### ISSUE THREAD

**Issue by Akodiat** [lorenzo-rovigatti/oxDNA#10]
Building with the romano contrib directory (using `make romano`) fails in `contrib/romano/src/Backends/MCMoves/Reappear`.
I assume this is because it still uses templates, but I couldn't quite figure out what changes were needed.

It is not really of an issue for me as I can just use the SourceForge release, but I thought I should make a note of it here.

**Comment by Akodiat** [comment]
Hi Lorenzo, thanks for such a quick response! Yeah, feel free to close the issue if you want. I wanted to use the patchy shape interaction, but as I wrote I can just use the old code for this.

**Comment by lorenzo-rovigatti** [comment]
Well, if you want to give it a shot you can have a look at the `breaking_changes.md` file in the `oxpy` branch. I tried to list the major changes there. It's not going to be easy though :-p

**Comment by lorenzo-rovigatti** [comment]
Regardless, this is a problem and I think we will have to port everything to the "new" oxDNA sooner or later. Therefore I'll leave the issue open.

**Comment by lorenzo-rovigatti** [comment]
This has been fixed in commit bbf50c9a5cc96b556a57f395932734ccd0ff3eba
