### ISSUE TITLE
Can't read configuration file from the examples [v3.6.1]

### ISSUE THREAD

**Issue by A-VER** [lorenzo-rovigatti/oxDNA#101]
Hello!
After installing and compiling the oxDNA, I tried to ran examples but failed to read the configuration file.
My code was like this:
` ./oxDNA ../examples/PSEUDOKNOT/inputMD1`
And I got this:
`INFO: seeding the RNG with 764352577
INFO: Initializing backend
INFO: Simulation type not specified, using MD
INFO: The generator will try to take into account bonded interactions by choosing distances between bonded neighbours no larger than 2.000000
INFO: Converting temperature from Celsius (20.000000 C°) to simulation units (0.097717)
INFO: Temperature change detected (new temperature: 20.00 C, 293.15 K), re-initialising the DNA interaction
INFO: pid: 19960
INFO: Aggregated I/O statistics (set debug=1 for file-wise information)
    0.000  B written to files
    0.000  B written to stdout/stderr
ERROR: Can't read configuration file 'generated.dat'`
After this I ran another two examples and got the same error.
My installation process was like this:
`cd oxDNA-3.6.1
mkdir build
cd build
cmake  -DPython=ON -DOxpySystemInstall=On -DG=ON -DINTEL=ON ..
make -j16`
And everything went ok.
Does anyone know what is going on? Thanks very much for your help!

**Comment by lorenzo-rovigatti** [comment]
Hi! The examples should be run from their own folder. You should change directory and then run oxDNA there:

```
cd ../examples/PSEUDOKNOT/
../../build/bin/oxDNA inputMD1
```

**Comment by A-VER** [comment]
> Hi! The examples should be run from their own folder. You should change directory and then run oxDNA there:
> 
> ```
> cd ../examples/PSEUDOKNOT/
> ../../build/bin/oxDNA inputMD1
> ```

Oh, I see! Thank you so much for helping!
