### ISSUE TITLE
oxDNA analysis tool: duplex angle plotter

### ISSUE THREAD

**Issue by AdaABen** [lorenzo-rovigatti/oxDNA#104]
Hello, i wanted to ask some information regarding the duplex angle plotter tool and how the angles are defined. when I get the output file, it is not really clear to me how to interpret the numbers I get. thank you in advance for any reply!

**Comment by AdaABen** [comment]
Thank you for your kind reply. I have another question. Is there a way to calculate the azimuthal angle between specific pairs of nucleotides using the existing tools or some other tool? Additionally, what is the best method to distinguish these angles and determine the direction of their deviation?

**Comment by ErikPoppleton** [comment]
Sorry for the delayed reply.

No, that is not a script that I have made.  If you end up writing something and think that it is general enough to include in OAT, I would be happy to consider a pull-request.

As far as direction of deviation goes, you will need to specify some sort of fixed reference frame based on the overall structure.  I would start by using `oat align` to align the whole trajectory, and then you could, for example, use the orientation of the first duplex in your structure, or if your structure has an obvious axis, use that as your reference to distinguish the direction of deviation.
