### ISSUE TITLE
Compute energy without running the simulation

### ISSUE THREAD

**Issue by swapnilbaral-git** [lorenzo-rovigatti/oxDNA#107]
**Is your feature request related to a problem? Please describe.**
I ran a LAMMPS/CGDNA simulation (oxDNA2) and considered comparing the energies computed by the simulation for a selected structure with the energies computed by standalone oxDNA2. I want to see that all energies computed by these two methods agree.

**Describe alternatives you've considered**
I have energies computed by LAMMPS/CGDNA. To obtain energy computed by oxDNA2, I ran energy minimization and used the energies corresponding to 0th step to make the comparison with LAMMPS/CGDNA computed energies. I see that kinetic energy agree but the potential energies do not. So I have two questions:

1) Is there a way to spit out the energies corresponding to a given confirmation/structure without running a simulation just by using a) oxview, or b) any script ?
2) My understanding is that there should be no conversion factor between oxDNA potential energy and LAMMPS potential energy. Please let me know if I am in correct. I want to mention that I am aware that oxDNA energies are computed per particle.

**Comment by lorenzo-rovigatti** [comment]
Hi!

1. I don't know of any third-party tools that can be used to compute the energy.
2. I'm not familiar with the LAMMPS implementation, but I would be surprised if they used different units of measurement.

Just out of curiosity by how much do they differ?

**Comment by ErikPoppleton** [comment]
I'm not sure if this is what you're looking for, but in oxDNA Analysis Tools there is `output_bonds` which given a configuration and an input file, uses the oxDNA energy model to compute the energy of each individual term in the interaction potential.  For example if you run
```
oat output_bonds input configuration.dat
```

You will get an output which looks something like:
```
#id1 id2 FENE BEXC STCK NEXC HB CRSTCK CXSTCK DH total, t = 607000000
0 1 0.0414132 0.0 -1.11994 0.0 0.0 0.0 0.0 0.0 -1.07852
0 2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.000134116 0.000134116
1 2 0.0456133 0.0 -1.14283 0.0 0.0 0.0 0.0 0.0 -1.09722
1 3 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.000369632 0.000369632
2 3 0.00818457 0.0 -1.22545 0.0 0.0 0.0 0.0 0.0 -1.21726
2 4 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.000244062 0.000244062
3 4 0.00311354 0.0 -1.34097 0.0 0.0 0.0 0.0 0.0 -1.33786
3 5 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.00030874 0.00030874
4 5 0.0064446 0.0 -1.33258 0.0 0.0 0.0 0.0 0.0 -1.32613
4 6 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.000630652 0.000630652
5 6 0.161738 0.0 -1.20651 0.0 0.0 0.0 0.0 0.0 -1.04477
5 7 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.000588574 0.000588574
...
```

The first two columns give the IDs of two particles which interact, and the subsequent columns give the value of each term from the potential used in the input file.
