### ISSUE TITLE
[DOCUMENTATION] Sequence Dependence of Cross-Stacking

### ISSUE THREAD

**Issue by alec-cook** [lorenzo-rovigatti/oxDNA#108]
Hello,

The oxDNA2_sequence_dependent_parameters.txt file provides modifiers for the stacking interaction between each pair of nucleotides. As I understand the notation, the parameter STCK_G_C modifies stacking in the dinucleotide 3'-GC-5', while STCK_C_G modifies 3'-CG-5'. I am assuming that these parameters refer specifically to the stacking between bonded neighbors; the difference between GC and CG is not well defined in the cross-stacking case, where the pair of nucleotides straddles two antiparallel strands.  

How, if at all, is sequence dependence considered for cross-stacking interactions? Is the orientation of the nucleotides considered at all (e.g. is the cross-stacking between two bases that mutually face one another in the 5' direction different than the interaction between the same two bases facing one another in the 3' direction)? 

Is coaxial stacking sequence-dependent in the same way as stacking between bonded neighbors?

The interaction DNA2ModInteraction, provided in /contrib/randisi, allows for a mod_stacking_multiplier to be defined. Does this  multiplier affect all stacking interactions (bonded, coaxial, cross), or just the stacking between bonded neighbors?

Thank you,
Alec

**Comment by lorenzo-rovigatti** [comment]
Hey there,

the cross- and coaxial-stacking interactions are both sequence-independent. About DNA2ModInteraction: the person who coded it left academia a few years back, I have no idea what it does.
