### ISSUE TITLE
[BUG] Installation Error when running 'make install'

### ISSUE THREAD

**Issue by Zehui127** [lorenzo-rovigatti/oxDNA#109]
**Describe the bug**
I'm installing oxDNA on the `Ubuntu 22.04.4 LTS`. 
`make -j4` works fine, but when running `make install `, the following errors appear

> make: *** No rule to make target 'install'.  Stop.

**To Reproduce**
```
# clone from the current master branch `https://github.com/lorenzo-rovigatti/oxDNA.git`
cd oxDNA         # enter the oxDNA folder
mkdir build      # create a new build folder. It is good practice to compile out-of-source
cd build
cmake ..         # here you can specify additional options, see next section
make -j4         # compile oxDNA. The -jX make option makes it compile the code in parallel by using X threads.

```
> [ 94%] Built target oxdna_common
> [ 96%] Built target oxDNA
> [ 98%] Built target DNAnalysis
> [100%] Built target confGenerator

`make install`

> make: *** No rule to make target 'install'.  Stop.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - oxDNA Version: current main branch
- cmake: 3.22.1
- make: GNU Make 4.3
- gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by lorenzo-rovigatti** [comment]
Hi! `make install` does nothing. As per the documentation, if the compilation succeeds you will find the executables in the `build/bin` folder.

**Comment by Zehui127** [comment]
Hi @lorenzo-rovigatti  thanks for replying. But I cannot run most of the examples provided with the oxDNA_analysis_tools cannot be found error, do I need to manually copy the source code of oxDNA_analysis_tools to the conda env?

**Comment by lorenzo-rovigatti** [comment]
Sorry, it was not clear that you needed to also install oat and the Python bindings. In this case you need to run `cmake .. -DPython=On` rather than `cmake ..`, and then `make install` at the end.

**Comment by Zehui127** [comment]
thanks a lot
