### ISSUE TITLE
[DOCUMENTATION] Interaction Potentials Definitions

### ISSUE THREAD

**Issue by simonecodispoti** [lorenzo-rovigatti/oxDNA#116]
Hi everyone, 
I started using oxDNA 2 years ago and I keep using it (together with the analysis tools) to probe ssDNA, dsDNA or more complex secondary structures.

In general, I would like to know **how every component of the interaction potentials is defined and computed**, because I couldn't find it in the documentation nor diving into the oxDNA source code. Is it an information already available somewhere? Could it be be rended explicit somewhere?

For example, when talking about _Debye-Huckel potential_, this can be computed as a per-nucletoide average using `output_bonds` a posteriori from the trajectory, but _what is the functional expression used to calculate it_? 

Thanks a lot for taking this into consideration,
I think that whoever is using oxDNA for research purposes would benefit from this.

Simone Codispoti

**Comment by lorenzo-rovigatti** [comment]
The functional forms are all in the original publications:

* [oxDNA1](https://pubs.aip.org/aip/jcp/article-abstract/137/13/135101/191221/Sequence-dependent-thermodynamics-of-a-coarse?redirectedFrom=fulltext)
* [oxDNA2](https://pubs.aip.org/aip/jcp/article-abstract/142/23/234901/193554/Introducing-improved-structural-properties-and?redirectedFrom=fulltext)
* [oxRNA](https://pubs.aip.org/aip/jcp/article-abstract/140/23/235102/73414/A-nucleotide-level-coarse-grained-model-of-RNA?redirectedFrom=fulltext)
* [oxNA](https://pubs.aip.org/aip/jcp/article/160/11/115101/3275728)

**Comment by simonecodispoti** [comment]
Thanks a lot @lorenzo-rovigatti!
You can close this issue.

Thanks again,
Simone
