### ISSUE TITLE
[BUG] Minor oversight in `get_input_parameter` in `RyeReader.py`

### ISSUE THREAD

**Issue by thoswope17** [lorenzo-rovigatti/oxDNA#119]
Hi,

The function `get_input_parameter` in [`RyeReader.py`](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/analysis/src/oxDNA_analysis_tools/UTILS/RyeReader.py) has an issue when requesting the value of a parameter whose name is a substring of a different parameter (e.g., `steps` as a substring of `newtonian_steps`) if the input file is written with keys provided in a certain order. As an example, if `parameter = "steps"` and the `steps` key precedes the `newtonian_steps` key in the input file, `get_input_parameter` will return the value of the `newtonian_steps` key instead of the intended value of `steps`.

I think a regex solution is something like this (but maybe there are oversights on my end as well as to how the input file can be structured; `pattern` might need changed to accommodate):

```python
import re

def get_input_parameter(input_file: str, parameter: str) -> str:
    """
    Gets the value of a parameter in an oxDNA input file
    
    Parameters:
        input_file (str): The path to the input file
        parameter (str): The parameter you want to get the value of

    Returns:
        (str): The value of the parameter
    """
    value = ''
    pattern = rf'^\s*{re.escape(parameter)}\s*=\s*([^#]*)' #regex pattern to be matched, attempting to strip comments made at end of a line if it is necessary
    with open(input_file) as fin:
        for line in fin:
            if not line.startswith("#"): #if uncommented line
                match = re.match(pattern, line) #attempt to match line to pattern
                if match:
                    value = match.group(1).strip() #store relevant contents of found match
    if value == '':
        raise RuntimeError("Key {} not found in input file {}".format(parameter, input_file))
    return value
```

(Type annotations could also be added where necessary.)

Apologies if this is unhelpful/rubs off nitpicky. This function is convenient to me to grab path information from the input file alone in in-house analysis that I've written and feel it might be worth reporting (but maybe it is not as helpful to others).

**Comment by ErikPoppleton** [comment]
Fixed in bca41abce999d46fa658620e2c99efb1e3c69c0c
