### ISSUE TITLE
[DOCUMENTATION] Two Repulsion Planes - CUDA 

### ISSUE THREAD

**Issue by juanitapombo** [lorenzo-rovigatti/oxDNA#120]
Hi all, 

I am struggling at understanding how to implement repulsion planes when relaxing a simple 6bp ds helix running MD in GPUs, and I suspect my issue is either PBC related or CUDA related. I wish to simulate this structure, (the initial configuration is centered within the simulation box of side length = 12), and constrain its dynamics between x = 3 and x = 9. In other words, following the documentation I have two repulsion planes sandwiching the structure described as follows:

```
{
type = repulsion_plane
particle = -1
stiff = 1.00
dir = -1, 0, 0
position = 9
PBC = 0
}
{
type = repulsion_plane
particle = -1
stiff = 1.00
dir = 1, 0, 0
position = -3
PBC = 0
}
```

When running MD, I receive the error: `ERROR: A cell contains more than _max_n_per_cell (12) particles. Please increase the value of max_density_multiplier (which defaults to 1) in the input file`

I have used `cells_auto_optimisation = false` and reduce the simulation box size in an attempt to circumvent this issue, but I inevitably get the error within the first few 100 thousand MD steps. 

Is there something else I am missing that could be causing this error? Thanks so much in advance for any guidance and feel free to point me to any examples/ additional documentation. 

For reference, the input script for the oxDNA 2019 release looks as: 

```
## SIM SPECIFIC
dt = 0.0001
max_backbone_force = 50
steps = 1e7
T = 300K
salt_concentration = 1

## INPUT/OUT FILES & OPTIONS
topology = init.top
conf_file = init.dat
lastconf_file = relaxed_last.dat
trajectory_file = relaxed_trj.dat
energy_file = relaxed_energy.dat
print_conf_interval = 1e4
print_energy_every  = 1e4

## COMPUTING OPTIONS
backend = CUDA
max_density_multiplier = 100
backend_precision = mixed
CUDA_list = verlet
CUDA_sort_every = 0
use_edge = 1
edge_n_forces = 1
cells_auto_optimisation = false
back_in_box=1

## SIM SPECIFIC 
interaction_type = DNA2
sim_type = MD
thermostat = john
verlet_skin = 0.1
newtonian_steps = 103
diff_coeff = 2.5
time_scale = linear
refresh_vel = 1
restart_step_counter = 1
max_io=500
use_average_seq = yes
seq_dep_file = asp.txt
external_forces = true
external_forces_file = forces.txt
```

**Comment by lorenzo-rovigatti** [comment]
Hi! Can you try setting `fix_diffusion = false`?

**Comment by juanitapombo** [comment]
Hi! Thanks for your response. Unfortunately I still get the same error. It looks to me like the simulation breaks when the structure approaches the edge of the box. I do see from the slurm output that there are no fix diffusion related messages. Could you explain to me how the simulation deals with boundaries when we set `fix_diffusion = false`?

I am attaching the error_conf.dat and init.top files (as .txt as required by GitHub) in case that helps. 
[error_conf.txt](https://github.com/user-attachments/files/16799370/error_conf.txt)
[init.txt](https://github.com/user-attachments/files/16799385/init.txt)
[relaxed_trj.txt](https://github.com/user-attachments/files/16799438/relaxed_trj.txt)

Thanks so much again!

**Comment by lorenzo-rovigatti** [comment]
Could you attach the whole folder? input and force files, plus topology and initial configuration?

**Comment by juanitapombo** [comment]
Here you go. Thanks!!

[repulsion_planes.zip](https://github.com/user-attachments/files/16799882/repulsion_planes.zip)

**Comment by lorenzo-rovigatti** [comment]
Thanks *a lot* for opening this issue. Surprisingly, the crash you observed was completely unrelated to the repulsion planes, but rather due to the initial configuration, which contains nucleotides aligned along a specific direction. This caused a crash because of a problem with a normalisation function. It should be fixed now.

**Comment by juanitapombo** [comment]
Thanks so much for the help! To carry out the simulation, would you recommend reinstalling oxDNA or perhaps avoiding these types of initial configurations / running a somewhat long MC relaxation before MD? 

Thanks again!

**Comment by lorenzo-rovigatti** [comment]
A few MC steps should be enough to get rid of the problem. I think it's a good habit to do that to speed up relaxation, regardless of this bug or of other issues you may encounter.
