### ISSUE TITLE
[BUG] PatchyBonds Observable Causes Crash

### ISSUE THREAD

**Issue by JeDeveloper** [lorenzo-rovigatti/oxDNA#121]
**Describe the bug**
When I try to run the DetailedPatchySwapInteraction in contrib/rovigatti with the attached files, the following occurs
```
(base) josh@Josh-Laptop:~/pypatchy_test/staged_big_octohedron_2024-08-28/T_0.01$ ~/git/oxDNA/build/bin/oxDNA input
INFO: seeding the RNG with 916930336
INFO: Initializing backend 
INFO: Simulation type: MD
INFO: The generator will try to take into account bonded interactions by choosing distances between bonded neighbours no larger than 2.000000
INFO: Parsing JSON observable file observables.json
INFO:    Observable file parsed
INFO: Setting the maximum IO limit to 5 MB/s
INFO: pid: 44378
INFO: DPS: Custom patches will be normalised
INFO: FS parameters: lambda = 1.000000, A_part = 14.778112, B_part = 0.000023
INFO: DetailedPatchySwapInteraction: species 0 has 1 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 1 has 6 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 2 has 0 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 3 has 0 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 4 has 0 particles and 4 patches
INFO: DetailedPatchySwapInteraction: species 5 has 12 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 6 has 0 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 7 has 0 particles and 8 patches
INFO: DetailedPatchySwapInteraction: species 8 has 8 particles and 24 patches
INFO: DetailedPatchySwapInteraction: species 9 has 0 particles and 12 patches
free(): invalid pointer


INFO: # Caught SIGNAL 6; setting stop = 1

Aborted (core dumped)

```

**To Reproduce**
Unzip the [attached files](https://github.com/user-attachments/files/16791147/example_files.zip) in a folder.
Edit `input` file to update `plugin_search_path` to your local `oxDNA/contrib/rovigatti`
Run in terminal `oxDNA input`
if the line `observables_file = observables.json` is removed from the input file, oxDNA runs as expected.

**Expected behavior**
DetailedPatchySwapInteraction and PatchyBonds observable should function as expected. 
I have previously run simulations with the same `observables.json` file so the problem is clearly the combination of the observable and this specific conf.
The starting conf rapidly explodes when I ran the simulation without observables.json, however an explodey conf should not cause a `free(): invalid pointer` error.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - oxDNA Version: latest version, commit 6052b17
- cmake version 3.16.3
- Make 4.2.1
- g++ 9.4.0

**Additional context**

**Comment by lorenzo-rovigatti** [comment]
Everything works fine on my box. Maybe you `git pull`d and recompiled the code but not the plugins?

**Comment by lorenzo-rovigatti** [comment]
Any news on this one?
