### ISSUE TITLE
[BUG] error on `make test_run` on WSL to install Python bindings

### ISSUE THREAD

**Issue by dave-doty** [lorenzo-rovigatti/oxDNA#122]
**Describe the bug**
When I follow the instructions to install the Python bindings for oxDNA (https://lorenzo-rovigatti.github.io/oxDNA/install.html), it seems to install correctly, but when I follow the next suggestion to run `make test_run`, I get this error:

```
(base) ddoty@g-quadruplex-24:~/download/oxDNA/build
$ make test_run
[ 92%] Built target oxdna_common
[ 94%] Built target DNAnalysis
[ 96%] Built target confGenerator
[ 98%] Built target oxDNA
[100%] Running build integration tests
/usr/bin/env: ‘python3\r’: No such file or directory
make[3]: *** [CMakeFiles/test_run.dir/build.make:71: CMakeFiles/test_run] Error 127
make[2]: *** [CMakeFiles/Makefile2:294: CMakeFiles/test_run.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/test_run.dir/rule] Error 2
make: *** [Makefile:169: test_run] Error 2
```

**To Reproduce**
Follow the instructions here: https://lorenzo-rovigatti.github.io/oxDNA/install.html
1. Clone the oxDNA repo.
2. On Windows, start a WSL prompt in the local repo folder.
3. `mkdir build`
4. `cd build`
5. `cmake -DPython=ON -DPYTHON_EXECUTABLE=~/anaconda3/bin/python ..` (I tried this when I noticed the error message references `/usr/bin/`, which has some other python executable that may have come with Ubuntu; I didn't specify `-DPYTHON_INCLUDE_DIR` because I have no idea what a "Python include directory" is.)
6. `make -j4`
7. `make install`
8. `make test_run`

**Expected behavior**
Tests pass.

**Desktop (please complete the following information):**
- OS: WSL2 on Windows 11, running Ubuntu 22.04
- oxDNA Version 3.6.1
- cmake: 3.22.1
- make: 
  ```
  $ make --version
    GNU Make 4.3
    Built for x86_64-pc-linux-gnu
  ```
- g++: `g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`
- python: Anaconda Python 3.12.4, installed in WSL in ~/anaconda3. But as I said, I think the issue might be that the installer is not recognizing that despite me specifying `-DPYTHON_EXECUTABLE=~/anaconda3/bin/python` to `cmake`.

**Comment by lorenzo-rovigatti** [comment]
I suspect that the issue is due to the different way Linux and Windows handle line endings. Does the code work, regardless of the outcome of `make test_run`? Can you try running one of the examples?
Unfortunately I don't have a working WSL to test the code on, but maybe @zoombya does?

**Comment by dave-doty** [comment]
> Does the code work, regardless of the outcome of make test_run?

What code? I was trying to do `make test_run` to see if my installation worked. I'm not sure what code you are referring to.

**Comment by lorenzo-rovigatti** [comment]
The oxDNA binary.

**Comment by dave-doty** [comment]
It runs although I don't know what input to give it:

```
$ oxDNA
ERROR: Usage is 'oxDNA input_file'
```

**Comment by lorenzo-rovigatti** [comment]
I tried installing WSL from scratch and I cannot reproduce the issue. Is it possible that you cloned the repo *outside* of WSL? If you did so, can you try cloning it directly on WSL?

**Comment by dave-doty** [comment]
> I tried installing WSL from scratch and I cannot reproduce the issue. Is it possible that you cloned the repo _outside_ of WSL? If you did so, can you try cloning it directly on WSL?

I tried twice:

1. Cloning in Windows using GitHub desktop, then copying that folder into my WSL home directory.
2. Cloning from a WSL prompt, but within the Windows file system (/mnt/c/Dropbox/git/).

I just now tried a third option (but on a different computer than I was using last week):

3. Cloning from a WSL prompt, within the "Linux-only" file system (/home/ddoty/git/).

Option 3 worked. However, I have not verified that options 1 and 2 failed on my current machine, only that they failed last week on my laptop while at the oxDNA workshop. Not sure if there is a subtle configuration difference between the machines. But since it appears to work if everything is done inside the WSL "Linux-only" filesystem, perhaps that should be part of the official installation instructions.

**Comment by lorenzo-rovigatti** [comment]
The problem is due to the different way line endings are handled in windows and linux. If you clone from windows, you'll end up with windows "line endings", and that will make linux's python complain.
It makes sense to add it to the docs though, thanks for testing it!
