### ISSUE TITLE
[BUG] output_bonds.py crashes

### ISSUE THREAD

**Issue by francescomambretti** [lorenzo-rovigatti/oxDNA#125]
Running the output_bonds.py script, provided in analysis/src/oxDNA_analysis_tools folder, results in "`TypeError: cannot unpack non-iterable NoneType object`".

It happens with CPU and as well with GPU oxDNA flavors (v 3.6.0). 
```
oxDNA_analysis_tools version: 2.3.0
Python version: 3.10.9
Package Numpy found. Version: 1.26.4
```

Take any kind of trajectory, but also with a single initial configuration such as the one reported in examples/HAIRPIN, and run: 
`python /path/to/oxDNA/analysis/src/oxDNA_analysis_tools/output_bonds.py input initial.conf `or
`python /path/to/oxDNA/analysis/src/oxDNA_analysis_tools/output_bonds.py input trajectory.dat`

This will result in some logging, some analysis and then:
```
None
Traceback (most recent call last):
  File "/home/fmambretti@iit.local/installed/oxDNA-GPU/examples/HAIRPIN/../../analysis/src/oxDNA_analysis_tools/output_bonds.py", line 208, in <module>
    main()
  File "/home/fmambretti@iit.local/installed/oxDNA-GPU/examples/HAIRPIN/../../analysis/src/oxDNA_analysis_tools/output_bonds.py", line 191, in main
    energies, potentials = output_bonds(traj_info, top_info, inputfile, visualize, conversion_factor, ncpus)
TypeError: cannot unpack non-iterable NoneType object
```
I am running these tests on Ubuntu 20.04

I am not sure whether this error could create any mistakes in the analysis itself.
Best regards

Francesco

**Comment by lorenzo-rovigatti** [comment]
I can't reproduce the bug on my box. Is it possible that you updated the code and then forgot to reinstall OAT with `make install`?

**Comment by francescomambretti** [comment]
The issue persists even re-installing everything from scratch. All tests are successfully passed. However, I have now tested the same on another machine with RedHatEnterprise 8.7 and the same works. 
Thanks for the help!

**Comment by lorenzo-rovigatti** [comment]
Can you post the cmake output of the machine where it doesn't work? The error could be due to different python versions (the one used to compile the code against and the one you are using to run the analysis)

**Comment by francescomambretti** [comment]
```
cmake .. -DPython=ON -DCUDA=ON -DCUDA_COMMON_ARCH=ON
[...]


-- Compiling in Release+Debug symbols mode
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Generating code for the following CUDA architectures: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70 sm_75 compute_70 compute_75
-- -gencode arch=compute_30,code=sm_30;-gencode arch=compute_35,code=sm_35;-gencode arch=compute_50,code=sm_50;-gencode arch=compute_52,code=sm_52;-gencode arch=compute_60,code=sm_60;-gencode arch=compute_61,code=sm_61;-gencode arch=compute_70,code=sm_70;-gencode arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
-- Adding the targets found in the /home/fmambretti@iit.local/installed/oxDNA-GPU/contrib/randisi folder
-- Adding the targets found in the /home/fmambretti@iit.local/installed/oxDNA-GPU/contrib/romano folder
-- Adding the targets found in the /home/fmambretti@iit.local/installed/oxDNA-GPU/contrib/rovigatti folder
-- Adding the targets found in the /home/fmambretti@iit.local/installed/oxDNA-GPU/contrib/tostiguerra folder
-- pybind11 v2.11.0 dev1
-- The detected Python's include dirs are: /home/fmambretti@iit.local/anaconda3/include/python3.10
-- Enabling Python bindings
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fmambretti@iit.local/installed/oxDNA-GPU/build

```

**Comment by lorenzo-rovigatti** [comment]
Thank you! Can you check that the python found by cmake is the same that you use when you launch oat scripts?

**Comment by francescomambretti** [comment]
It's the same!
/home/fmambretti@iit.local/anaconda3/bin/python3.10

However, the important thing i that the analusis code workes elsewhere. Thanks!

**Comment by lorenzo-rovigatti** [comment]
Thank you! Then I have no idea what was going on. Luckily you made it work, but let me know if you have any other issues.
