### ISSUE TITLE
Stopping a simulation upon satisfying a condition

### ISSUE THREAD

**Issue by alec-cook** [lorenzo-rovigatti/oxDNA#126]
Hello,

Is it possible to force an oxDNA simulation to terminate early when a condition is reached? For instance, when a specific base pair is broken, or when the distance between two nucleotides exceeds a certain value? I know that this functionality exists for FFS simulations, but I'm wondering if it's possible to conduct MD simulations with similar stop conditions. 

Thank you,
Alec

**Comment by lorenzo-rovigatti** [comment]
Hi! It is possible with oxpy, but not with the standalone binary. With oxpy you can define your own observable (see [here](https://lorenzo-rovigatti.github.io/oxDNA/oxpy/extending/observables.html)), or access the output of observables defined in the input file (by setting their `id` field and then using [ConfigInfo's get_observable_by_id](https://lorenzo-rovigatti.github.io/oxDNA/oxpy/extending/observables.html). You can then call the observable's `get_output_string` function while the simulation is running, parse its output and possibly end the simulation if some condition is met.
