### ISSUE TITLE
[BUG] Custom base in oxNA using the new topology

### ISSUE THREAD

**Issue by FranzHanrieder** [lorenzo-rovigatti/oxDNA#128]
**Describe the bug**
I would like to introduce a custom nucleotide into a complex of DNA and RNA. My goal would be that the new base does not interact with any other base. I tried to follow the instructions in the oxDNA documentation. To test this I used the following example as a topology file:
10 2 5->3
A(-10)(-10)AA id=1 type=DNA circular=false
UUGCU id=2 type=RNA circular=false
However, when I want to start the simulation, I always get the following error message: “ERROR: Too many particles found in the topology file (should be 10), aborting”
Therefore I wanted to ask if there is something wrong with my .top, .dat or input file or if it could be a bug in the code.

**To Reproduce**
Below I have added the folder with all the files I have used:
[test_newtopo.zip](https://github.com/user-attachments/files/17072920/test_newtopo.zip)

**Expected behavior**
By running the simulation over the terminal with the command oxDNA inputMC, it should execute a normal MC simulation, but shows the error message instead.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - oxDNA Version: latest

**Comment by lorenzo-rovigatti** [comment]
Thanks a lot for the report!

@eryykr , I did a quick test and it appears that this is a bug in the DNA/RNA hybrid interaction. Can you have a look?

**Comment by eryykr** [comment]
Thanks for letting me know guys. Submitted PR, should be fixed.

**Comment by lorenzo-rovigatti** [comment]
Thank you Eryk! The fix has been merged, and the example provided by @FranzHanrieder works just fine.

**Comment by FranzHanrieder** [comment]
Thank you guys very much!
