### ISSUE TITLE
[BUG] Failed compilation with Cuda and c++ 11.1.0

### ISSUE THREAD

**Issue by mmguar** [lorenzo-rovigatti/oxDNA#13]
**Describe the bug**
Compilation fails while creating common_generated_cuda_decive_utils.cu.o for errors in stl_pair.h

**To Reproduce**
1. Followed the installation procedure recommended on the repo
2. Try with and without  DCUDA_COMMON_ARCH
3. 
**Expected behavior**
Compilation :)

**Desktop (please complete the following information):**
 - OS: Linux
- cmake 3.20.2 make 4.3 g++ 10.2.0 c++ 11.1.0

**Additional context**
I report here the error code. 
```
Building NVCC (Device) object src/CMakeFiles/oxDNA.dir/CUDA/Interactions/oxDNA_generated_CUDAInteractionFactory.cu.o
/usr/include/c++/11.1.0/bits/stl_pair.h(460): error: argument list for class template "std::pair" is missing

/usr/include/c++/11.1.0/bits/stl_pair.h(460): error: expected a ")"

/usr/include/c++/11.1.0/bits/stl_pair.h(460): error: template parameter "_T1" may not be redeclared in this scope

/usr/include/c++/11.1.0/bits/stl_pair.h(460): error: expected a ";"

/usr/include/c++/11.1.0/bits/basic_string.h(6050): error: argument list for class template "std::__cxx11::basic_string" is missing

/usr/include/c++/11.1.0/bits/basic_string.h(6050): error: expected a ")"
[...]
100 errors detected in the compilation of "/home/matteo/Downloads/oxdna_bleed/oxdna-code/oxDNA/src/CUDA/Backends/MD_CUDABackend.cu".
Compilation terminated.
CMake Error at oxDNA_generated_MD_CUDABackend.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/matteo/Downloads/oxdna_bleed/oxdna-code/oxDNA/build/src/CMakeFiles/oxDNA.dir/CUDA/Backends/./oxDNA_generated_MD_CUDABackend.cu.o
```

I am not entirely sure if the bug lies in oxDNA or possibly in this c++ 11.1.0, maybe you can help me a little here.

**Comment by lorenzo-rovigatti** [comment]
Hi! What do you mean by "c++ 11.1.0"? Is that your g++ version? Or the CUDA version?

**Comment by mmguar** [comment]
Hi Lorenzo. Apologies for being unclear.
g++ and gcc in the path end up being the cuda versions
`[matteo@matteOs4 build]$ g++ --version
g++ (Arch Linux 10.2.0-3) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[matteo@matteOs4 build]$ type g++
g++ is hashed (/opt/cuda/bin/g++)
`
aliasing them to /usr/bin/gcc shows version 11.1.0, which should be correct, but does not solve compilation issues.
As for nvcc
`[matteo@matteOs4 build]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
`

**Comment by lorenzo-rovigatti** [comment]
OK, it seems you have a mismatch between the compiler and the lib it uses to compile. If you look at the errors, they refer to the path `/usr/include/c++/11.1.0`, which seems to indicate that the system compiler is g++ 11.1.0, which is not the one used to compile the code. I'm not sure how to solve this, but it doesn't seem strictly related to oxDNA. Is this a cluster node? Is there anyone who can help you with this?

**Comment by mmguar** [comment]
Hm, I understand that this is not an oxDNA problem most likely and I appreciate the support.
I removed the wrong bindings to gcc and g++, now they all show version 11.1.0, which is the one installed system-wide. The previous ones were the one shipped with cuda, which overrode the system ones through a poor PATH specification.
So now I believe I am compiling oxDNA with gcc 11.1.0 (--version confirms it), but I do still get the same errors.

Unfortunately it is my own computer and thus I have to debug it myself. I am more so looking for any pointers towards the right direction. It might also just be that arch is too "nightly" and cuda will not compile correctly before an update.

**Comment by lorenzo-rovigatti** [comment]
As far as I know CUDA 11.3 is incompatible with g++ > 10. You'll have to install an older version and set it as the default (if you using ubuntu there is the handy `update-alternatives` command that can help you switch between versions).

**Comment by mmguar** [comment]
Thank you for the pointer. 
`update-alternatives` is unfortunately unavailable in arch, but the solution was to create a simlink in /usr/local/bin for gcc, g++ and cc (see here): 
`sudo ln -s $(which gcc-5) /usr/local/bin/gcc
sudo ln -s $(which g++-5) /usr/local/bin/g++`
Unfortunately that is not enough as the command that gives the error specifies  `-ccbin /usr/bin/cc`, so it was necessary to temporary replace /usr/bin/cc:
`sudo mv /usr/bin/cc /usr/bin/cc.new
sudo cp /usr/bin/cc-10 /usr/bin/cc`
Compilation is fine then.
If anyone was to stumble upon this again, please remember to revert to your standard gcc with:
`sudo rm /usr/bin/cc
sudo mv /usr/bin/cc.new /usr/bin/cc
sudo rm /usr/local/bin/gcc /usr/local/bin/g++
hash -r`
