### ISSUE TITLE
[BUG] oxDNA_PDB does not apply residue type 5 when using new top format

### ISSUE THREAD

**Issue by lgruenewald** [lorenzo-rovigatti/oxDNA#132]
**Describe the bug**
Using oxDNA_PDB with the new top format does not apply the residue_type 5 to the 5' end. Resulting in the 5' residue not being converted to a terminal residue. Applies to both single and double strands.

**To Reproduce**
1. Generate conf and top based on the new format. 
For a simple single strand:
top:
3 1 5->3 
CAG circular=False

conf:
t = 0
b =  12.0 12.0 12.0
E = 0. 0. 0.
8.263177546519714 11.6322189403938 8.905487231628687 -0.07146215698109333 -0.6330475481637039 0.7708073442070544 0.6460451290590713 0.5594028104892707 0.5193208900436734 0.0 0.0 0.0 0.0 0.0 0.0
8.270595263126046 11.153776369957157 8.661104772371305 -0.5034990080668057 -0.19903399174299796 0.840758121582296 0.6460451290590713 0.5594028104892707 0.5193208900436734 0.0 0.0 0.0 0.0 0.0 0.0
8.16324036500093 10.629963994840084 8.608373153383098 -0.7442481679334395 0.3105959058117577 0.5912908318422437 0.6460451290590713 0.5594028104892707 0.5193208900436734 0.0 0.0 0.0 0.0 0.0 0.0

2. Run oxDNA_PDB: oat oxDNA_PDB top conf 53 

**Expected behavior**
The generated .pdb should have a 5' end residue signified by e.g. DC5. However the residue remains unmodified and is listed as DC instead. 

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu
 - oxDNA Version 3.6.1
- cmake version 3.22.1/GNU Make 4.3/g++ 11.4.0

**Additional context**
The issue can be circumvented by adjusting the if statement during residue_type assignment. In the original code the statement checks as follows: ` if nucleotide == strand.monomers[0] and not strand.is_circular():` 
If the above line is modified to ` if nucleotide == strand.monomers[0]:` the 5' modifications are applied.

**Comment by ErikPoppleton** [comment]
Thanks for catching this!  The logic in oxDNA_PDB was actually correct, but there was an error in file parsing and type conversion in the topology parser.  Fixed in a168f8d604d6db4d43e7b588651552b60d270554
