### ISSUE TITLE
[FEATURE REQUEST] Add PDB → oxDNA file format conversion in OAT

### ISSUE THREAD

**Issue by Lucandia** [lorenzo-rovigatti/oxDNA#133]
Hi,

 First of all, thank you for developing OAT, it's an excellent tool. While OAT already supports converting oxDNA file formats to PDB, it currently lacks the function to convert PDB files to oxDNA. PDB is a widely-used format, and adding this conversion feature would further streamline the workflow.

Additionally, having PDB → oxDNA conversion available through the scripting interface would make it much easier to integrate this functionality into custom pipelines and automation scripts.

While TacoxDNA does offer PDB → oxDNA conversion, it has not been updated to support the new oxDNA topology format, and it currently lacks a scripting interface.

We already discussed alternative approaches in lorenzo-rovigatti/tacoxDNA#44, but we believe this functionality could be a valuable addition to OAT.

I would be happy to contribute to the implementation if needed!

Thank you so much for your work!

Best,  
 Luca

**Comment by ErikPoppleton** [comment]
It shouldn't be too difficult of a task to take the base orientation calculation from Taco and apply it to the OAT monomer data structure so it's easy to write out either topology format.  If you're okay with me superseding Taco functionality like that, @lorenzo-rovigatti, I can write it up sometime this week.

**Comment by lorenzo-rovigatti** [comment]
Sure, I'm fine with that. I think it's better to have things streamlines in OAT rather than in a separate package.

**Comment by ErikPoppleton** [comment]
Added in e0084bc259ff139ef0b7fe5d38902a72c7198b41 Give it a try and let me know if I missed anything in my testing!
