### ISSUE TITLE
[BUG] Nucleotide tracking: issue with particle_position observable

### ISSUE THREAD

**Issue by SimonGrall** [lorenzo-rovigatti/oxDNA#140]
**Describe the bug**
I am tracking the ith nucleotide of a DNA strand with 2 approaches that, I thought, should give identical results.

1) I generate trajectory.dat and browse through the file with some code snippet to retrieve the XYZ position of the ith nucleotide at each time step.

2) I generate a custom observable in the input file tracking the ith nucleotide, adding the following to my input file (for the 40th nucleotide in a double strand DNA here) :
data_output = {
     print_every = 100
     name = TRACK.txt
     col_1 = {
             type = step
             }
     col_2 = {
             type = particle_position
             particle_id = 39
             absolute = 1
             }
}

When looking at the results, I get reasonable measurements for the method 1, with a position roughly coherent with ~0.3 nm/nucleotides, as expected for DNA. But not for method 2, with about 2 times less nm/nucleotides and a different distribution in space at the end. I suspect I am messing up at some point with the indexing of particles, but could  not get information on this. Oxdna was compiled in 2018 for method 1, and in 2024 for method 2, if that make any difference. Aside this, all parameters are identical.

I am sorry if this is a stupid request, by I am just out of things to check now. 
Thank you in advance, whoever ends up helping.

Simon.

**Comment by lorenzo-rovigatti** [comment]
I'm not sure what the problem could be without having a look at the input files, at the custom script you use and at your expected/actual output. Can you add some details?

**Comment by SimonGrall** [comment]
Hello Lorenzo,
Here attached the input files, last conf files and ext force used, as well as the script retrieving the ith particle (40th in that case on a 20T double strand DNA).
The file track_ushort.py has as input trajectory.dat, some index counter, the list of particle to track (here only 1 element) and some inputfile of our own storing some basic information.

Thank you for having a look at this.
Simon.

[OXDNA2024.zip](https://github.com/user-attachments/files/17658846/OXDNA2024.zip)
[OXDNA2018.zip](https://github.com/user-attachments/files/17658847/OXDNA2018.zip)

**Comment by lorenzo-rovigatti** [comment]
OK. What do you want to see by tracking the position of a single nucleotide? I thought it had something to do with the average position of that specific nucleotide, which should be affected by the external forces, so that if those vary than you would expect to see some differences between the two simulations

**Comment by SimonGrall** [comment]
I updated the ZIP files to include the generated.top files.

**Comment by lorenzo-rovigatti** [comment]
Thank you, but there are still information missing. How do I analyse the results with track_ushort.py? What do I have to compare between the two simulations?

**Comment by SimonGrall** [comment]
Sorry for the oversights.
Track ushort outputs a track of only the followed nucleotide. This should be compared with the output of the observable particle_position.
track_ushort.py takes as inputs (obtained through sys.argv): trajectory.dat, i, [40], *homemade_inputfile*
This will create a file track-Mol1-i.txt to be compared with the output of the observable, for the positions of the tracked nucleotide. (Here tracking the 40th nucleotide).

As for thet homemade_inputfile, it should contain the following:

nb_bases_=40
nb_basesOpposite_=0
nb_molecules_=1
nb_moleculesOpposite_=0

**Comment by lorenzo-rovigatti** [comment]
The two simulations start from different initial configurations, use different external forces and don't set the seed of the random number generator. Is there any reason why you expect the two trajectories to be the same?

**Comment by SimonGrall** [comment]
They simulate the same DNA strand, with the same forces applied on it. I expect the average position over lets say 10^9 steps to be the same with respect to the position of the harmonic trap (i.e. where the DNA stand is attached).
 The only difference in forces is the 3D coordinate of the origin, i.e. the location of the DNA strand within the box. The boxes have different sizes, and should be roughly in the middle, far enough from the edges. As long as the simulation goes on correctly, I thought that the dynamic of a double stranded DNA attached at one end would be the same no matter the box coordinates, no?

**Comment by lorenzo-rovigatti** [comment]
I used your script on a trajectory generated with a simulation where I also used the `particle_position` observable and the two methods yield exactly the same positions. I can try to help you if you can manage to prepare an example where the bug can be reproduced with short-ish simulations, and if you tell me exactly what I have to do to reproduce it.

**Comment by SimonGrall** [comment]
Ok, I think I am starting to see that my problem is due to my specific setup, not OxDNA. There is just one thing I am still not clear about: in the trajectory.dat file, distances are given in simulation units? What about the distance given in observables particle position? I get the same values for both now as well, but one multiplied by 0.8518, the conversion factor between nm and oxDNA units. I thought both would be in simulation units. Sorry for the mess, and thank you again for your help.

Below is the snippet for the particle position observable in the input_file:

data_output_2 = {
     print_every = 100
     name = TRACK.txt
     col_1 = {
             type = step
             }
     col_2 = {
             type = particle_position
             particle_id = 9
             absolute = 1
             }
}

**Comment by lorenzo-rovigatti** [comment]
No, the code knows nothing about "real units". Can you attach a trajectory and a TRACK.txt file where this happens? Or (even better) a complete example I can use to test this?

**Comment by SimonGrall** [comment]
Ok, this part with the unit is clarified thank you. As expected, it was a mess on my part. 
After thorough check, it seems that the issue is coming from the way particles are indexed in trajectory.dat for double strand DNA (I don't see issues for single stranded ones). I think I did a mistake where I assumed the particle 40 would be the one at the free side, but it actually is the particle 20, since apparently they are ordered such that their index is a constant sum (of 19 here). I am sorry for the unnecessary bother, thank you again for your time. 
Simon.

**Comment by lorenzo-rovigatti** [comment]
Nucleotides in the trajectory are listed in the same order they are listed in the topology file.

**Comment by SimonGrall** [comment]
Ok, so, I thought I got it but maybe not, the topology file  is not so explicit on which nucleotide is attached to which for double stranded. I understand that strands are written in the 3-5 order. For example, for a dt8ds I get:

16 2
1 T -1 1
1 T 0 2
1 T 1 3
1 T 2 4
1 T 3 5
1 T 4 6
1 T 5 7
1 T 6 -1
2 A -1 9
2 A 8 10
2 A 9 11
2 A 10 12
2 A 11 13
2 A 12 14
2 A 13 15
2 A 14 -1

In that case, who is neighbor to who between strands? I assumed both to be 3-5, so that the base line 0 (1 T -1 1) is in principle attached to the opposite strand's base number 8 (2 A -1 9), is that correct?

**Comment by lorenzo-rovigatti** [comment]
No, that's not correct. Real DNA strands forming a duplex need to have opposite polarity, so that the 3' of one strand binds to the 5' of the second strand. It is the same in oxDNA, which means that in your case the first nucleotide is paired with the last one.

**Comment by SimonGrall** [comment]
Okay, then it means in terms of bases indexes, that I will have the following pairing for my previous example:
 0   1   2    3   4    5   6  7
 T   T    T   T   T    T   T  T
 |   |    |   |   |    |  |  |
 A   A   A   A   A   A  A  A
15 14 13 12 11 10  9  8

**Comment by lorenzo-rovigatti** [comment]
Yes, that's right.

Il lun 23 dic 2024, 16:02 SimonGrall ***@***.***> ha scritto:
