### ISSUE TITLE
[BUG] input file problems in the MPI example 

### ISSUE THREAD

**Issue by zoombya** [lorenzo-rovigatti/oxDNA#15]
**Describe the bug**
Example file in /examples/PARALLEL_TEMPERING requires the `backend_precision` parameter to be set.

**To Reproduce**
1. compile oxDNA with MPI settings
2. try run example

**Comment by lorenzo-rovigatti** [comment]
This specific bug has been fixed in commit 3641080, although the example does not completely successfully. Unfortunately I did not code up the backend myself and I don't think I'd be able to fix it.
