### ISSUE TITLE
observable_file input option

### ISSUE THREAD

**Issue by zoombya** [lorenzo-rovigatti/oxDNA#18]
Add an **observable_file** option to the oxDNA input file to have a way of storing observables,
and exchanging \ building them with 3d party tools like ox-view.

**Comment by lorenzo-rovigatti** [comment]
Commit 1c065cbc6474c361a6ab8a1c6b8fab5bf04fddc6 adds a new `observables_file` option that can be used to specify a JSON file containing additional outputs. Here is an example:

```json
{
  "output_1" : {
    "print_every" : "10000",
    "name" : "hb_energy.dat",
    "cols" : [
      {
        "type" : "step",
        "units" : "MD"
      },
      {
        "type" : "hb_energy"
      }
    ]
  },
  "output_2" : {
    "print_every" : "1000",
    "name" : "pot_energy.dat",
    "cols" : [
      {
        "type" : "step"
      },
      {
        "type" : "potential_energy"
      }
    ]
  }
}

```

**Comment by lorenzo-rovigatti** [comment]
Commit ca24b8b4295c8028be2da76f648078455f68ba56 added an `analysis_observables_file` that is used by `DNAnalysis` and has the same syntax as `observables_file` (which is used by `oxDNA`).
I decided to keep the two separated to make it harder to overwrite files by accident.
