### ISSUE TITLE
Additional simulation parameters exposed via oxpy

### ISSUE THREAD

**Issue by ErikPoppleton** [lorenzo-rovigatti/oxDNA#20]
I would request the following parameters be exposed through the oxpy interface;

- [x] Box size for the currently loaded configuration through `ConfigInfo`
- [x] Strand index as written in the topology file for a `molecule` object

These will be particularly important once the ANM-oxDNA fork is merged in as they are used in the conversion from oxDNANM back to PDB.

**Comment by lorenzo-rovigatti** [comment]
I have added `config_info.box` to access the box object, but also `config_info().box_sides` for convenience.
In addition, molecules now have two more attributes, `id` (which is 0-based) and `topology_id` (which is 1-based and it's the index listed in the topology file).
