### ISSUE TITLE
[BUG] K (kinetic energy) value difference between energy_file and the conf headers

### ISSUE THREAD

**Issue by RodenLuo** [lorenzo-rovigatti/oxDNA#22]
**Describe the bug**

Hi, I notice in MD, there are three different places that output energy values (U, K, U+K), console, `energy_file`, and conf headers. The console and energy_file outputs are identical. However, the U (potential energy) values are different in energy_file and conf headers. Is this desired or not? Thanks! 

**To Reproduce**

Using this test [example](https://github.com/lorenzo-rovigatti/oxDNA/tree/master/test/DNA/DSDNA8/MD), but change the following line (print_energy_every ) to 1e5 to match the print intervals.

https://github.com/lorenzo-rovigatti/oxDNA/blob/0db1c91ad565b298d85746d348cf179019d97a19/test/DNA/DSDNA8/MD/quick_input#L27

I get different K values.

![image](https://user-images.githubusercontent.com/8460424/183100762-edd3447d-b2ee-4a70-994f-b326e59bdf93.png)

**Expected behavior**

From my understanding of the doc, they should be the same. If they are designed to be different, why? 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - oxDNA Version: 3.3
- cmake/make/compiler versions: cmake version 3.16.3, GNU Make 4.2.1, gcc version 9.4.0

(This is also the case for oxDNA 2.3.2 on both Ubuntu 20.04.4 LTS and Windows 10.)

**Additional context**

The difference comes from that when printing energy_file, in the below line, the _directions.size() is 3, while when printing the conf header, it is 0.

https://github.com/lorenzo-rovigatti/oxDNA/blob/0db1c91ad565b298d85746d348cf179019d97a19/src/Observables/KineticEnergy.cpp#L36

And hence the code snippet below is not executed when printing the conf header.

https://github.com/lorenzo-rovigatti/oxDNA/blob/0db1c91ad565b298d85746d348cf179019d97a19/src/Observables/KineticEnergy.cpp#L41-L43

See live debugging screenshots below: 

![image](https://user-images.githubusercontent.com/8460424/183101924-e3910073-4a79-43b4-a427-9709469c6116.png)

![image](https://user-images.githubusercontent.com/8460424/183101940-012f9b5c-2094-4e16-aa89-d8f886a03176.png)

**Comment by lorenzo-rovigatti** [comment]
Roden, thanks a lot for the report. Looking at the git history it looks like this thing has been broken essentially forever, and you are the first one noticing! It should be fixed now.

**Comment by RodenLuo** [comment]
Thanks for the quick fix!
