### ISSUE TITLE
Potential problems in the doc for oat clustering 

### ISSUE THREAD

**Issue by RodenLuo** [lorenzo-rovigatti/oxDNA#23]
Hi, 

https://github.com/lorenzo-rovigatti/oxDNA/blob/c1b152fd9c6911ba79423761b6cede5bbfbd92ff/analysis/paper_examples/clustering/README.md#L7

This line gives the error: 

```bash
$ oat mean -f oxDNA -o mean_all.dat trajectory.dat
usage: mean.py [-h] [-p num_cpus] [-o output_file] [-d deviation_file] [-i index_file] [-a alignment_configuration] trajectory
mean.py: error: unrecognized arguments: -f trajectory.dat
```

If I remove `-f oxDNA`, it seems to be working. 

```
$ oat mean -o mean_all.dat trajectory.dat
INFO: oxDNA_analysis_tools version: 2.0.3
INFO: running config.py installed at:  /home/luod/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/config.py
INFO: Python version: 3.8.13
WARNING: Some scripts will not run with Python versions earler than 3.8.  You have {}, please update your environment
INFO: Package Numpy found. Version: 1.23.1
WARNING: Some packages need to be installed/updated.
```

Same for 

https://github.com/lorenzo-rovigatti/oxDNA/blob/c1b152fd9c6911ba79423761b6cede5bbfbd92ff/analysis/paper_examples/clustering/README.md#L13

I have to remove `input_rna`.

Is this a typo/leftover from copy-paste or something related to non-proper installation?

**Comment by ErikPoppleton** [comment]
Hi Roden, you're correct.  I didn't update that README file when I updated the script invocations.  I have updated the README, thank you for pointing it out.
