### ISSUE TITLE
PCA inconsistencies between paper, doc, and code

### ISSUE THREAD

**Issue by RodenLuo** [lorenzo-rovigatti/oxDNA#24]
Paper: 

[Link](https://academic.oup.com/nar/article/48/12/e72/5843822#205314419)

> Finally, the PCA script outputs a .json file for the oxView tool, which displays arrows on the structure corresponding to the sum of a user-defined number of components weighted by their respective eigenvalues.

Doc: 

[Snippet link](https://github.com/lorenzo-rovigatti/oxDNA/blob/f401ae77ffaac1309c14191f9905889cfec64e50/analysis/paper_examples/PCA/README.md#L24)

> This will produce an oxView json file that plots arrows on the structure which corresond to the weighted sum of the first n components.  n can be set by modifying the SUM variable in the pca.py script.  To view in the viewer, drag and drop the mean structure, topology and PCA json files onto the viewer window. 

From the old code [snippet](https://github.com/sulcgroup/oxdna_analysis_tools/blob/48307ae355dace3fe97f7af51e2f16a329a1579a/pca.py#L180-L182), the above is true.

From the current code [snippet](https://github.com/lorenzo-rovigatti/oxDNA/blob/f401ae77ffaac1309c14191f9905889cfec64e50/analysis/src/oxDNA_analysis_tools/pca.py#L223-L225), the json files are written for each Principal Component for the top N (hard coded, can be changed by the user) components, and the weight for each component is the **square root** of its respective eigenvalue rather than the eigenvalue itself. It makes more sense, as the eigenvalue itself is the variance along that component, while the square root of the eigenvalue can be thought of as the standard deviation. Sorry to be picky... just that it might save someone else's time from being confused.

If I am not mistaken, it also makes more sense to visualize each component separately. As for each principal component, what the visual does essentially is that it distributes (or more mathematically, it projects) the high dimensional eigenvector to all nucleotides. Hence the visual shows the **variance** (deviation) of each nucleotide from its **reference** (mean/centroid) position. The **length** of the three-element vector (xyz vector) projected on each nucleotide corresponds to the **importance** of that nucleotide in terms of the principal component of interest. From another point of view, the total variance of each nucleotide is also distributed to all the principal components. 

Taking together, the number of the significant principal components reveals the number of the significant motion patterns (the collective motion or say the interplay between all nucleotides). Then for each motion pattern (i.e., for each principal component), the arrows overlaying on the reference positions of all nucleotides visually reveal the deviations from the reference positions. With the data on hand, one can also visualize from another point of view, by showing all the projected xyz vectors for each nucleotide. In this way, it will become clear that some nucleotides are actively involved in several motion patterns, some other nucleotides are involved in just one, and the rest are not involved in any. 

If the above understanding is correct, then a better way to plot the vectors is to place the center of the line on the nucleotide and draw an arrow on both ends of the line.

![image](https://user-images.githubusercontent.com/8460424/184079152-5038e8ba-ce92-4251-9828-2bd33a1e03e2.png)

For the Holliday junction example, the PC0 reveals the scissoring motion of the "arms". PC1 reveals the motion of the "fist" perpendicular to the other duplex. PC1 reveals the motion of the "fist" parallel to the other duplex.

![image](https://user-images.githubusercontent.com/8460424/184079191-97042bcc-26b1-44d9-94b0-57fdb005f1d6.png)

If we overlay PC0, PC1, and PC2 on each nucleotide with different colors, we can then clearly see that the single-stranded overhanging "fist" is contributing to all three motion patterns while most of the rest are contributing to just one.

![image](https://user-images.githubusercontent.com/8460424/184079240-cd96ddf9-5679-4a3b-bbc4-eb76701ac294.png)

**Comment by ErikPoppleton** [comment]
Hi Roden,

Thanks for the ideas.  I have stuck with only printing one arrow per principal component to keep visuals more clear when overlaying data as you show in your final image.  I have updated the README of the PCA example to be more clear and added a `-n` flag to the script, which specifies how many components to print to oxView JSON files (with the default remaining 1).
