### ISSUE TITLE
`dt` missing from input file documentation

### ISSUE THREAD

**Issue by rkruegs123** [lorenzo-rovigatti/oxDNA#25]
the `dt` variable is missing from the documentation for the input file: https://lorenzo-rovigatti.github.io/oxDNA/input.html

Also, it would be nice if the "documentation" label was available to public users for submitting issues

**Comment by lorenzo-rovigatti** [comment]
Thanks for all the issues, I'll work on them. As for the label, as far as I know it's a github "feature" ([see here](https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner)). I think the only of doing that would be to have multiple issue templates, one for each label (or label combination). I'll think about it!

**Comment by rkruegs123** [comment]
Sounds great, thank you!
