### ISSUE TITLE
`use_average_seq` error

### ISSUE THREAD

**Issue by rkruegs123** [lorenzo-rovigatti/oxDNA#27]
I set `use_average_seq = true` in the input file explicitly, and I received the following error:

``ERROR: Mandatory key `seq_dep_file` not found``

It seems as though the error checking is flipped here, as `seq_dep_file` should only be required if `use_average_seq = false`. Happy to provide an explicit input file example of it's helpful.

**Comment by lorenzo-rovigatti** [comment]
This is actually a proper bug, as the field would only accept "0" for false and "1" for true, while any other value would lead to unpredictable behaviour. I'm fixing it now.
