### ISSUE TITLE
Recompilation after `git pull`

### ISSUE THREAD

**Issue by rkruegs123** [lorenzo-rovigatti/oxDNA#29]
Since this repository is updated quite frequently, I think there should be a section in the documentation for how to recompile the executable after a `git pull`. E.g., does the user have to do anything special, or can they just repeat the instructions in `install.md`?

**Comment by lorenzo-rovigatti** [comment]
Thanks for the suggestion! I have added the following paragraph to the installation doc page:

### Updating a local copy

If you cloned the repository to install oxDNA, your local copy can be updated with the following commands:

```bash
cd oxDNA        # enter the oxDNA folder
git pull        # use git to synchronize your repo with the online one
cd build        # enter the build folder (see above)
make -j4        # compile the updated source
```

If you also want to update `oxpy` don't forget to run `make install` after the compilation.
