### ISSUE TITLE
[BUG] ERROR: Cannot convert '0.' to a number

### ISSUE THREAD

**Issue by RodenLuo** [lorenzo-rovigatti/oxDNA#32]
**Describe the bug**

When using tacoxdna [CanDo → oxDNAbeta](http://tacoxdna.sissa.it/CanDo_oxDNA), at the input MC relax, I met the following error. 

```bash
ERROR: Cannot convert '0.' to a number
```

**To Reproduce**

Feed [this cndo file](https://cando-dna-origami.org/tetrahedron.cndo) to tacoxdna [CanDo → oxDNAbeta](http://tacoxdna.sissa.it/CanDo_oxDNA), and try to relax the generated result. 

**Expected behavior**

Run through relax

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - oxDNA Version: 
    ```
    INFO: RELEASE: v3.3
    INFO: GIT COMMIT: c1b152f
    INFO: COMPILED ON: 05/08/22
    ```
- cmake/make/compiler versions: cmake version 3.16.3/GNU Make 4.2.1/gcc version 9.4.0

**Additional context**

This can be easily fixed using two `sed` commands on the conf file for this example. 

```
sed -i 's/0\. /0 /g' tetrahedron.cndo.dat
sed -i 's/0\.$/0/g' tetrahedron.cndo.dat
```

This can also be fixed in tacoxdna [CanDo → oxDNAbeta](http://tacoxdna.sissa.it/CanDo_oxDNA). 

But the cause is deep in the fast_double_parser. It's not treating `0.` as a number, see https://github.com/lemire/fast_double_parser/pull/65. My proposed solution there should have almost no side effects (at least in the case of oxDNA) except fixing this error. Because from the next time step onwards, that block is never reached.

**Comment by RodenLuo** [comment]
So, `0.` is considered an invalid number, see https://github.com/lemire/fast_double_parser/issues/40. This might involve some fixing from the converter's side.

**Comment by lorenzo-rovigatti** [comment]
Hey Roden, thanks for the report. I'll add the wonfix label here, since this is a "feature" of one of the lib oxDNA includes. However, I have committed a change to tacoxDNA so that the cando tool uses `0.0` in place of `0.`. I'll try to update the webserver as well, but that may take more time.
