### ISSUE TITLE
Just a quick fix for oxView overlays 

### ISSUE THREAD

**Issue by simonecodispoti** [lorenzo-rovigatti/oxDNA#38]
Hi all! I was visualizing some overlays with oxView (the `output_bonds` json files): some of them work just fine, but others present a blank scale in the colorbar. I'll post here two examples of what I mean by _working_ and _not working_.

As always, thank you all for considering this issue! In alternative I could produce the colorbar separately via `matplotlib`, but if it's easy fixable would be nice.

<img width="1108" alt="Schermata 2022-09-25 alle 13 55 26" src="https://user-images.githubusercontent.com/62181811/192142180-c14dba72-65ab-4df9-9e50-976ea20fb493.png">
<img width="1108" alt="Schermata 2022-09-25 alle 13 55 59" src="https://user-images.githubusercontent.com/62181811/192142181-04eba1d4-bbed-4431-aafd-59d17fec76d7.png">

**Comment by lorenzo-rovigatti** [comment]
Hey Simone, I think you should post this issue to the [oxview's repo](https://github.com/sulcgroup/oxdna-viewer) rather than here!
