### ISSUE TITLE
[BUG] generate-RNA.py

### ISSUE THREAD

**Issue by aspitaleri** [lorenzo-rovigatti/oxDNA#51]
**Describe the bug**
The script to generate conf and top is complaining about model.h missing:

python2 generate-RNA.py
IOError: [Errno 2] No such file or directory: '/usr/local/oxDNA-3.4.2/oxDNA/legacy/UTILS/../src/model.h'

**To Reproduce**
Run the script within the directory UTILS using python2

**Expected behavior**
It should generate conf and top filles from sequence txt

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - oxDNA Version 3.4.2
- cmake/make/compiler versions

**Additional context**
The script works properly fixing in base.py line 25
model = os.path.join(os.path.dirname(__file__), "../../src/model.h")
and line 47:
model = os.path.join(os.path.dirname(__file__), "../../src/Interactions/rna_model.h")

**Comment by lorenzo-rovigatti** [comment]
Thanks for the report! Those files are in the `LEGACY` folder and are not supported any more. I urge you to use `confGenerator`, `utils/generator-sa.py` or (better) external tools such as [https://sulcgroup.github.io/oxdna-viewer/](oxview)
