### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by philipturner** [lorenzo-rovigatti/oxDNA#53]
The research paper says mixed precision is generally more numerically stable than single, but was that claim tested specifically for oxDNA? Single precision takes a different trajectory (butterfly effect), but in MD mixed only really helps with energy minimization.

Maybe this could improve quaternions: https://hal.science/hal-02470766/document

**Comment by lorenzo-rovigatti** [comment]
I'm not sure what you mean by "butterfly effect", but I'm familiar with the idea that the same configuration evolved differently will generate trajectories whose mutual "distance" diverges exponentially with time.

As for the difference in the numerical stability of single vs mixed precision, this is a plot of my phd thesis that shows the energy of an NVE simulation performed with oxDNA with single, mixed and double precision on GPUs:

[precision.pdf](https://github.com/lorenzo-rovigatti/oxDNA/files/10701380/precision.pdf)

About your last point, note that the CUDA backend of oxDNA uses quaternions.

**Comment by philipturner** [comment]
> As for the difference in the numerical stability of single vs mixed precision, this is a plot of my phd thesis that shows the energy of an NVE simulation performed with oxDNA with single, mixed and double precision on GPUs:

My issue is that numerical stability and energy conservation are different. If you're connecting this to a thermal bath, small energy deviations won't matter. I'm worried about numerical stability in quaternion math being an "ill-structured problem". Similar to the reason eigenvalue decomposition always occurs in FP64.

**Comment by lorenzo-rovigatti** [comment]
I don't exactly agree with the dismission of the effect of "small energy deviations" on the simulation performance, since a better energy conservation makes it possible to increase the integration time step and/or decouple the thermostat (which can increase particle diffusion and can therefore help simulating diffusion-limited systems). 
Having said that, we periodically re-orthonormalise orientations to limit the kind of numerical issues I think you are referring too, although I'm not an expert in this matter.

**Comment by philipturner** [comment]
> better energy conservation makes it possible to increase the integration time step and/or decouple the thermostat

I have a GPU that has zero double precision, and I'm trying to port your algorithm to another package. If it's at least possible, the CPU -> GPU jump will outweigh this performance hit.

**Comment by lorenzo-rovigatti** [comment]
Yes, the raw speed-up should be rather large in that case. Also note that there are ways of doing calculations in double precision with only single-precision registers. It is rather cumbersome, but it could be useful in some stability-critical parts of the code.

**Comment by philipturner** [comment]
> It is rather cumbersome, but it could be useful in some stability-critical parts of the code.

Actually you can emulate the entire thing with IEEE compliance. I've confirmed that [it's possible](https://github.com/philipturner/metal-float64), just not worth my time. Double-single requires less effort. But even that requires nonzero effort, which I'd like to avoid.
