### ISSUE TITLE
Stacking Strength for Individual Nucs (General Question)

### ISSUE THREAD

**Issue by skyminer360** [lorenzo-rovigatti/oxDNA#54]
Hello again--

The sequence parameter file(s) allows us to change the bonding strengths between A, G, C and T. Is there a way to change bonding strengths for individual nucleotides? Let's say I don't want nucs 14 and 15 to stack with each other, but I still want them to hybridize to their complements and stack to their neighbors (13 and 16, respectively). Is this possible?

Kind regards
Daniel

**Comment by lorenzo-rovigatti** [comment]
Hi! Nope, that's unfortunately not possible at the moment.

**Comment by skyminer360** [comment]
Alright, thanks for the quick reply :)

Daniel
