### ISSUE TITLE
[FEATURE REQUEST] a question about oat oxDNA_PDB -p

### ISSUE THREAD

**Issue by HalseyWang** [lorenzo-rovigatti/oxDNA#57]
Hi, I encountered this problem when using this script, how can I solve it, thank you very much!!! LOL
Can this code be enabled by multi-core calculations like other codes?

oat oxDNA_PDB -p 80 1.top r1_conf.dat 53 -H
usage: oxDNA_PDB.py [-h] [-o OUTPUT] [-H] [-u] [-1] [-r RMSF_BFACTOR] topology configuration direction [pdbfiles]
oxDNA_PDB.py: error: unrecognized arguments: -p

Best regards,
Yue

**Comment by ErikPoppleton** [comment]
Hi Yue,

This script only converts a single frame to a single frame, so there's nothing to parallelize.  I suppose it could be modified to convert a trajectory to a PDB trajectory, however be warned that the output file sizes would be absolutely enormous.

**Comment by ErikPoppleton** [comment]
That being said, there was a documentation error in that oxDNA_PDB was missing from the command line interface documentation.  It has been added.

**Comment by HalseyWang** [comment]
Thank you very much!
