### ISSUE TITLE
(OAT Question) Computing Twist between bp

### ISSUE THREAD

**Issue by thoswope17** [lorenzo-rovigatti/oxDNA#58]
Hi,

Sorry if this is misplaced... I work with Daniel Hollis and I believe he's asked questions here before.

We have recently been studying helical pitch/twist angles. I noticed in a build of standalone oat (before the oxDNA + oat merge) that there used to be a function in UTILS/geom.py called get_turn_per_bp that we think might have been used to compute this.

We were wondering if this is applicable at all to oxDNA2 model (we think we found a formula for helicity vector in oxDNA1 model in paper: https://arxiv.org/abs/1009.4480 ). I thought maybe not as this function cruxes on backbone-backbone vector of the two bp, which makes more sense in oxDNA1 model than oxDNA2 model, but maybe I don't yet fully understand it.

Let me know if anything is unclear.

Thanks,
Tommy Swope

**Comment by supers1x** [comment]
Hi, supporting infomation from this paper may help   _J. Chem. Phys. 146, 214902 (2017)_

**Comment by thoswope17** [comment]
Thank you both for the info. The supplement to that paper is very helpful/relevant to us, and I was unaware of it (only the main article). We will let you know if we do end up writing code relevant to this.

**Comment by ErikPoppleton** [comment]
Great, thanks!  I'll go ahead and close this, but feel free to keep responding or open a new issue if you have further questions/issues.
