### ISSUE TITLE
make: *** No rule to make target install. Stop.

### ISSUE THREAD

**Issue by jmarlhens** [lorenzo-rovigatti/oxDNA#62]
Dear oxDNA Team,

I am currently facing an issue with the installation process of the oxDNA package. I have followed the provided instructions and successfully compiled the code using make -j4. However, when I attempt to run make install, I receive the following error message:

`make: *** No rule to make target `install'.  Stop.`

Consequently, I am unable to proceed with the installation of the oxDNA package.

Here is some information about my environment:

    Operating System: macOS 13.1 (22C65)
    CMake Version: cmake version 3.25.2
    Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
    Python Version: Python 3.9.15

I have tried searching for possible solutions, but I have been unable to find a way for this issue. I would appreciate any help, or I would like to know if it is a common issue.

Thank you for your time and support.

Best regards,
Jérémie Marlhens

**Comment by ErikPoppleton** [comment]
Hi Jérémie,

`make install` is only for the Python control (oxpy) and analysis (oat) code.  If you intend to install those, you need to include `-DPython=1` in your `cmake` invocation
