### ISSUE TITLE
[BUG] Truncated trajectory

### ISSUE THREAD

**Issue by Boyu-Liu03** [lorenzo-rovigatti/oxDNA#67]
**Describe the bug**
Sometimes OxDNA (web-browser version) produces a trajectory file that is truncated to 10 configurations of 10k steps to a total of 100k steps, with different input total_steps and print_config steps. 

**To Reproduce**
1. I ran simulations 
2. Here are the input files: 
[V3.1_51_NC_T_R.log](https://github.com/lorenzo-rovigatti/oxDNA/files/12653621/V3.1_51_NC_T_R.log)
[V3.1_51.NC.T.R traj log.pdf](https://github.com/lorenzo-rovigatti/oxDNA/files/12653622/V3.1_51.NC.T.R.traj.log.pdf)

However, I have also seen this issue with different input files under the same simulation parameter file: 
[V3.1_51_NC_T_R_input.txt](https://github.com/lorenzo-rovigatti/oxDNA/files/12653996/V3.1_51_NC_T_R_input.txt)
But also different input files with different simulation parameter files. 

**Expected behavior**

I expect the simulation to run and come back successful, but when downloading the trajectory, notice the incredibly small size of usually around 14mb compared to around 300mb that I usually get for other simulations using the same simulation parameters. Then, I expect that on the total jobs list, that the final configuration is greyed out and unavailable dispite the simulations ran successfully. 

**Desktop (please complete the following information):**
 - OS: [macOS Monterrey]
 - oxDNA Version [Latest web-browser]
- cmake/make/compiler versions

**Additional context**
I have also emailed the oxdnahelp email account about this issue with specific job identification numbers too.

**Comment by lorenzo-rovigatti** [comment]
If you look at the last part of the log file you can see that the simulation crashes with an "out-of-memory" error. The box size you are using is most likely too big,

**Comment by ErikPoppleton** [comment]
To follow up, the 10 configurations you're seeing are from the 10k Monte-Carlo steps that the relaxation protocol on the webserver begins with to remove excluded volume problems.  If you have specific problems with the webserver version, you should send an email to the address listed in the FAQ page, they can help more with webserver-specific problems.

**Comment by Boyu-Liu03** [comment]
Oh okay so sorry about the confusion then. Thank you all so much for the quick response!

**Comment by Boyu-Liu03** [comment]
I will be using the email address moving forward!
