### ISSUE TITLE
Benchmarking performance: hilbert sorting, lists, force, thermostat etc

### ISSUE THREAD

**Issue by swapnilbaral-git** [lorenzo-rovigatti/oxDNA#74]
**What is the documentation missing?**
The meaning behind different terms that are used to benchmark the performance such as Hilbert sorting, Lists, Force, First step, Thermostat etc. 

**Additional context**
While trying to benchmark the performance (time/step) of DNA of various number of nucleotides(nt), I noticed that the time/step is higher for 3200 nt than 4800 nt . I wanted to understand what was the reason this so I began looking deeper. I saw that together with time/step, more info is written in the log files such as  Hilbert sorting, Lists, Force, First step, Thermostat etc. In my case it takes more time to compute Lists in 3200 nt than 4800 nt (while computation time of all other parameters are lower in 3200 nt. But I could not tell why exactly was this happening. So I started wondering what is actually being done in part of the code such as during Hilbert sorting, Lists ... etc. Please let me know where I can read about this.

**Comment by ErikPoppleton** [comment]
I don't think there is a comprehensive guide to performance optimization anywhere, unfortunately.  Something to add to the list of things to add to the documentation.  That being said, Lorenzo wrote a paper on the optimization of the GPU code, which you can find [here](https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.23763).  

In your specific case I would guess that the way to optimize the performance would be to play with the `verlet_skin` parameter in the input file.  This controls the balance between the size of each particle's neighbor list and how frequently the list needs to be updated (larger list -> longer force calculation, but updating the list is really slow).  You probably already know this, but the list of input parameters can be found in the [documentation](https://lorenzo-rovigatti.github.io/oxDNA/input.html#).  `Verlet_skin` is under "Core Options".

**Comment by swapnilbaral-git** [comment]
Thanks for the comment. I saw that I have used larger box size for 3200 nt than 4800 nt. I have not used any systematic method to decide the box size. Can you please tell me what is the best way to determine the required box size for DNA of different length ? 

Also, what is the way to optimize the value of verlet_skin in the input ? I am not sure what are the possible values of this parameter and which metric should I compare for different values of verlet_skin.

**Comment by ErikPoppleton** [comment]
The box needs to be large enough that the DNA cannot interact with itself through the periodic boundary.  As a rule-of-thumb, we usually go 1.5x largest dimension of the structure, but that's slightly overkill, you can go a bit smaller, but watch out for weird interactions.

The [default input file](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/analysis/example_input_files/input_run) that I use has `verlet_skin=0.5` which I have found to generally be pretty good.  If I am trying to optimize it, I usually vary it from 0.1 to 1.5.

**Comment by lorenzo-rovigatti** [comment]
I have added [this](https://lorenzo-rovigatti.github.io/oxDNA/performance.html) page to the docs. I'll try to add more info in the future.
