### ISSUE TITLE
[FEATURE REQUEST] Can we adjust the range of Debye cutoff?

### ISSUE THREAD

**Issue by churchyuan** [lorenzo-rovigatti/oxDNA#83]
The article (Introducing improved structural properties and salt dependence into a coarse-grained model of DNA) shows that the Debye cutoff is three times the Debye length. Can we change this cutoff to other constant numbers? 
Sometimes, the complex structure needs a more extended range.

**Comment by churchyuan** [comment]
And if we can get the DH_energy output like HAIRPIN example, we use hb_energy.

**Comment by lorenzo-rovigatti** [comment]
As it is now, it can't be done without recompiling the code. I guess I can add an option that can be used to override the factor of 3. I'll do it as soon as I can. However, note that the code will run a lot slower since increasing the cut-off will also increase the average number of neighbours per particle.

**Comment by churchyuan** [comment]
Thanks. And if there is an option for recording the total DH energy in the system. I notice that in general we have the kinetic energy, potential energy and total energy. And I learned from HAIRPIN example, the energy of the hydrogen bond can be output by hb_energy. Are there some commands in input file can be used to output the DH energy? And then I can compare the DH energy difference among the conformation to make sure the adjustment of Debye length is useful.

**Comment by ErikPoppleton** [comment]
There is also an observable option to output all the energies.  It's called `pair_energy` and can be added to an observable during a simulation or calculated from a trajectory just like `hb_energy`.  The documentation for it is [here](https://lorenzo-rovigatti.github.io/oxDNA/observables.html#Interaction-energy-between-pairs-of-particles).  You can also use `oat bond_analysis` to extract this information from a trajectory file.  If you want to write your own script that does something similar, the way to call the observable through the oxpy interface can be found [here](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/analysis/src/oxDNA_analysis_tools/output_bonds.py#L71)

**Comment by lorenzo-rovigatti** [comment]
There is a new option `debye_huckel_rhigh` that sets the distance at which the smoothing of the Debye-Hucker repulsion begins, and defaults to three times the Debye screening length.

**Comment by churchyuan** [comment]
Thanks. I ran it yesterday, and it worked very well.
