### ISSUE TITLE
[BUG] oxDNA can not run on GPU

### ISSUE THREAD

**Issue by TruongChien** [lorenzo-rovigatti/oxDNA#86]
**Describe the bug**
I try to simulate DNA structure with oxDNA, it can work well with CPU
But, it's fail when running on GPU
ERROR message: "The selected device is not available for computation"

![error_oxdna_GPU](https://github.com/lorenzo-rovigatti/oxDNA/assets/62794870/73dfd16d-a727-40fe-adfd-a3546a467aa5)

**Desktop (please complete the following information):**
 - OS: Linux
 - oxDNA Version 3.6.0
 - cmake/make/compiler versions: 3.16.3/4.2.1
 - GPU: RTX A6000

Could you please help me to check what is the potential issues!
Thank you very much for your support!
Best regards,

**Comment by lorenzo-rovigatti** [comment]
Hi! Do you have a single CUDA device? Can you post the output of the `nvidia-smi` command?

**Comment by TruongChien** [comment]
Hi, Thank you very much for prompt reply!
After many tries, I figured out the problem was related to my gcc version, which was too old. After updating to the latest version it seems to be compatible with the latest version of oxDNA. Also, -DCUDA_COMMON_ARCH=OFF got my oxDNA working properly again.
Honestly, oxDNA works very effectively and stably! 
Thank you very much for your works and I'm really looking forward to oxDNA's next updates.
