### ISSUE TITLE
[BUG] analysis/tests/test.sh missing files

### ISSUE THREAD

**Issue by synapticdecor** [lorenzo-rovigatti/oxDNA#89]
**Describe the bug**
Running test.sh fails at certain tests because oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found. Log below :)
All other tests from the documentation pass and everything else seems to be running fine (have run quite a few oxDNA sims for trajectories) but just wanted to check if this is expected or whether my oxpy install had failed somewhere.  

**Desktop**
 - OS: Debian 12 headless 
 - oxDNA Version 3.6.0
- cmake version 3.25.1
- Python 3.9.18
- cmake -DCUDA=ON -DCUDA_COMMON_ARCH=OFF -DPython=ON -DOxpySystemInstall=On ..

**LOG**
(xando) cjna@ebiand:~/oxDNA/oxDNA-3.6.0/analysis/tests$ ./test.sh
Testing align...
OK

Testing backbone_flexibility...
OK

Testing bond_analysis...
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
AN ERROR OCCURED

Testing mean and deviations...
OK

Testing centroid with indexing...
OK

Testing contact_map...
OK

Testing distance and clustering (this one takes a while because of the plot)...
OK

Testing duplex_finder...
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
AN ERROR OCCURED

Testing duplex_angle_plotter...
FileNotFoundError: [Errno 2] No such file or directory: 'angles.txt'
AN ERROR OCCURED

Testing generate_force...
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
AN ERROR OCCURED

Testing minify...
OK

Testing multidimensional_scaling_mean...
OK

Testing output_bonds...
oxpy.core.OxDNAError: Mandatory key `seq_dep_file_RNA' not found
AN ERROR OCCURED

Testing pca
OK
Testing subset_trajectory...
OK

Testing superimpose...
OK

**Comment by ErikPoppleton** [comment]
@eryykr Is this something that got added by your model?  That key didn't used to be required.

**Comment by zoombya** [comment]
we should check for more occurrences, cause oxview also recently broke for same reason.

**Comment by eryykr** [comment]
Yes this came with the hybrid model, but it should only be required when interaction_type = NA. I'll take a closer look.

**Comment by eryykr** [comment]
We also added something like this to DNAInteraction.cpp (line 240)

**Comment by lorenzo-rovigatti** [comment]
@synapticdecor thank you very much for pointing out this issue/bug. It should be fixed now.

**Comment by synapticdecor** [comment]
Sorry for being absent during its solving, but no problem! Thank you guys for creating and maintaining such a sick program :)
