### ISSUE TITLE
> Thanks for the report! That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.

### ISSUE THREAD

**Issue by Azzzzzz11** [lorenzo-rovigatti/oxDNA#92]
> Thanks for the report! That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.

Yes, I added the line `use_average_seq = 1` in my input file. 
The above is the error after I added the average base. LOL~

Best regards,
Yue

_Originally posted by @HalseyWang in https://github.com/lorenzo-rovigatti/oxDNA/issues/56#issuecomment-1442713940_

**Comment by Azzzzzz11** [comment]
My input file =“input” I found it in folder “simulation”
every time I put something I want to simulate， There will be a file called “input” in simulation. And I change“ use_average_seq=0” to “use_average_seq=1” ，it didnt work. After that， I check the input file，it recovered.
Am I find a wrong input file. Could u help please？
BEST WISHES
CHEN

**Comment by lorenzo-rovigatti** [comment]
It is not clear what you are asking. Can you please edit your post so that we can understand what's going on?

**Comment by Azzzzzz11** [comment]
> It is not clear what you are asking. Can you please edit your post so that we can understand what's going on?

Describe the situation
 1.ERROR: Mandatory key `seq_dep_file' not found, exiting
   I put the example into the website，there will be file ”input“ in the folder“simulation”. And I put ”use_ average_seq=1“into the 
   ”input“ before running oxDNA. When I tried to run oxDNA，it‘s still will be  ERROR: Mandatory key `seq_dep_file' not found, 
   exiting， after that I check the changed file“input”，the line “use_average_seq=1“ disappeared. the file”input“ seems be   
   recovered. 

2. http://tacoxdna.sissa.it/Examples "Tiamat-oxDNA”
 ## Assuming DNA
## Assuming Tiamat version 2
Traceback (most recent call last):
 File "/home/tacoxdna/git/tacoxDNA/src/Tiamat_oxDNA.py", line 453, in
 data = load(f_out)
 File "/usr/local/lib/python3.6/json/__init__.py", line 296, in load
 return loads(fp.read(),
 File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
 return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
Some errors have been detected, output not generated

**Comment by Azzzzzz11** [comment]
> It is not clear what you are asking. Can you please edit your post so that we can understand what's going on?

ok sir， and I’m sorry about that I’m a rookie of computer.

**Comment by lorenzo-rovigatti** [comment]
I'm sorry but this is still not very clear to me. I don't know what you are trying to do, nor how, and your post contains errors from oxDNA and tacoxDNA (which is a different software).

**Comment by Azzzzzz11** [comment]
![微信图片_20240312194601](https://github.com/lorenzo-rovigatti/oxDNA/assets/162581552/b8878ec6-ba52-4c99-a9dd-3338bdcc1a52)
![微信图片编辑_20240312194110](https://github.com/lorenzo-rovigatti/oxDNA/assets/162581552/5f234e65-4c8d-402d-af51-dde39e04befb)
![微信图片编辑_20240312194330](https://github.com/lorenzo-rovigatti/oxDNA/assets/162581552/3f6bc7ca-dd69-457a-a6a9-044e75930e6e)
![微信图片编辑_20240312194510](https://github.com/lorenzo-rovigatti/oxDNA/assets/162581552/e7497ba0-b314-4708-89b5-a9a12c37152d)

**Comment by Azzzzzz11** [comment]
> I'm sorry but this is still not very clear to me. I don't know what you are trying to do, nor how, and your post contains errors from oxDNA and tacoxDNA (which is a different software).
I put some pictures

**Comment by Azzzzzz11** [comment]
> I have the impression that you are not launching oxDNA yourself, but rather using other tools to do that. I've never used anything but the command line to launch oxDNA, so I can't help you here. You should refer to the people who built the tools you are using. @zoombya , maybe you can help us?

ok I understand thank you！

**Comment by ErikPoppleton** [comment]
oxServe uses a [pre-built input file](https://github.com/sulcgroup/ox-serve/blob/master/resources/input_cuda_relax) and [doesn't allow](https://github.com/sulcgroup/ox-serve/blob/4e34e12848bf7dfe63d3b4964c04c89fd51926c6/main.ts#L59) most options to be changed.  This was done to make it streamlined for fast relaxation (it's not meant for production simulations).  If you want full control over your simulations from a scripting interface, you should be using oxpy.  @zoombya wrote a nice tutorial on simulation notebooks [here](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/examples/OXPY_Jupyter/literate_sim.ipynb)

**Comment by Azzzzzz11** [comment]
> oxServe uses a [pre-built input file](https://github.com/sulcgroup/ox-serve/blob/master/resources/input_cuda_relax) and [doesn't allow](https://github.com/sulcgroup/ox-serve/blob/4e34e12848bf7dfe63d3b4964c04c89fd51926c6/main.ts#L59) most options to be changed. This was done to make it streamlined for fast relaxation (it's not meant for production simulations). If you want full control over your simulations from a scripting interface, you should be using oxpy. @zoombya wrote a nice tutorial on simulation notebooks [here](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/examples/OXPY_Jupyter/literate_sim.ipynb)

Thank you very much！ I will take a good look at this tutorial.
