### ISSUE TITLE
[BUG] Insufficient Oxpy Cmake Error Message

### ISSUE THREAD

**Issue by JeDeveloper** [lorenzo-rovigatti/oxDNA#94]
Low priority issue. Error message does not contain information on error.
**Describe the bug**
On ASU's Sol supercomputer, i tried to run cmake to prep compilation of python bindings, but it failed with a blank error message
**To Reproduce**
With the following modules on ASU Sol Supercomputer (or some equivalent thereof) installed

Run (equivalent on your machine)
`(pypatchy) [jrevan21@c051:~/oxDNA/build]$ cmake .. -DPython=ON -DCuda=ON -DNATIVE_COMPILE=ON`
after some general cmake messages, got error
```-- Found PythonInterp: /home/jrevan21/.conda/envs/polycubes/bin/python (Required is at least version "3.9") 
CMake Error at oxpy/pybind11/tools/FindPythonLibsNew.cmake:147 (message):
  Python config failure:

Call Stack (most recent call first):
  oxpy/pybind11/tools/pybind11Tools.cmake:50 (find_package)
  oxpy/pybind11/tools/pybind11Common.cmake:180 (include)
  oxpy/pybind11/CMakeLists.txt:208 (include)
```

**Expected behavior**
I was actually able to resolve this issue by specifying `-DPYTHON_EXECUTABLE` and `-DPYTHON_INCLUDE_DIRS`, but nothing in the error message would have led me to this solution. The error message should be more descriptive.

**Desktop (please complete the following information):**
```
(pypatchy) [jrevan21@c051:~/oxDNA/build]$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```
working from oxDNA commit
`35682563d2068295c8d1fc77cc12299772dcb21e`

**Comment by lorenzo-rovigatti** [comment]
Unfortunately I cannot reproduce the bug (nor I can access ASU Sol). Can you attach files with the output of the following commands (given in clean folders)?

`cmake .. -DPython=On`

`cmake --trace-expand .. -DPython=On`

P.S. -DNATIVE_COMPILE=On does nothing. Native compilation is ON by default, and you can disable it with -DNATIVE_COMPILATION=Off

**Comment by lorenzo-rovigatti** [comment]
Any update on this one?

**Comment by JeDeveloper** [comment]
Sorry, this one kind of fell off my rader.
I tried reproducing the issue and wasn't able to do so (perhaps cmake updated?, so we can consider this issue closed.
