### ISSUE TITLE
oxDNA observable: radial distribution function

### ISSUE THREAD

**Issue by AdaABen** [lorenzo-rovigatti/oxDNA#95]
Hi,
Would it be possible to have additional information about the "Radial Distribution Function" Observable? How it is actually computed? I find confusing the 'axes' option:

DOC: https://lorenzo-rovigatti.github.io/oxDNA/observables.html#radial-distribution-function 

```
Radial distribution function []

type = rdf: the observable type.
max_value = <float>: maximum distance to consider.
bin_size = <float>: bin size for the .
[axes = <string>]: axes to consider in the computation. Mind that the normalization always assumes 3D sytems for the time being. Possible values are x, y, z, xy, yx, zy, yz, xz, zx.

```

How are the axes defined? Why it is not possible to consider all the directions? Isn't usually the g(r) computed considering the euclidean metric in the 3d space? (both x,y,z)

This is the result I got for a dsDNA of approx 20 base pairs:

<img width="664" alt="Screenshot 2024-03-22 alle 16 35 40" src="https://github.com/lorenzo-rovigatti/oxDNA/assets/164526896/1af2fe75-8ad7-4315-acc6-c8dca90975f6">

It is rather strange that the g(r) doesn't start from 0, but instead has a rapid decrease.

Thanks a lot for the attention!

**Comment by lorenzo-rovigatti** [comment]
Hi there! As you can see from the fact that there are square brackets around it, `axes` is optional and it's usually needed only if you are looking at some specific crystal-forming systems. Just omit it and you should be good to go.
Either than that the radial distribution function is defined in the usual way (see *e.g.* [here](https://en.wikipedia.org/wiki/Radial_distribution_function) ).
Note that for DNA and RNA the rdf is computed using each nucleotide's centre of mass. About your plot: did you set `axes` to some value?

**Comment by lorenzo-rovigatti** [comment]
Do you have any updates? Can I close the issue?
