### ISSUE TITLE
observable structure factor not found

### ISSUE THREAD

**Issue by AdaABen** [lorenzo-rovigatti/oxDNA#96]
Hi, when I try to print the observable "structure_factor" oxDNA gives this error message:

`ERROR: Observable 'structure_factor' not found. Aborting`

Has the observable simply changed name? Or there is some different issue?

Thanks a lot!

**Comment by lorenzo-rovigatti** [comment]
That's a typo in the docs, thanks for catching it! It should (and now does) read `Sq` and not `structure_factor`.
